

import Workspace from "../models/Workspace.js";
import User from "../models/User.js";
import Invite from "../models/Invite.js"
import jwt from "jsonwebtoken";
export const inviteToWorkspace = async (req, res) => {
  try {
    const { workspaceId } = req.params;
    const { email } = req.body;

    const workspace = await Workspace.findById(workspaceId);
    if (!workspace) {
      return res.status(404).json({ message: "Workspace not found" });
    }

    // check inviter is member
    const isMember = workspace.members.some(
      (id) => id.toString() === req.user.id
    );
    if (!isMember) {
      return res.status(403).json({ message: "Not a workspace member" });
    }

    const userToInvite = await User.findOne({ email });
    if (!userToInvite) {
      return res.status(404).json({ message: "User not found" });
    }

    const alreadyMember = workspace.members.some(
      (id) => id.toString() === userToInvite._id.toString()
    );
    if (alreadyMember) {
      return res.status(400).json({ message: "Already a member" });
    }

    // create invite
    const invite = await Invite.create({
      workspace: workspaceId,
      email,
      invitedBy: req.user.id,
      expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      token: "temp",
    });

    // sign invite token
    const inviteToken = jwt.sign(
      {
        inviteId: invite._id,
        workspaceId,
        inviteeId: userToInvite._id,
      },
      process.env.JWT_INVITE_SECRET,
      { expiresIn: "7d" }
    );

    invite.token = inviteToken;
    await invite.save();

    res.status(200).json({
      success: true,
      inviteLink: `http://localhost:5173/accept-invite/${inviteToken}`,
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Invite failed" });
  }
};

export const acceptInvite = async (req, res) => {
  try {
    const token = decodeURIComponent(req.params.token);
    if (!token) return res.status(400).json({ message: "Token required" });
//     👉 Invite acceptance does NOT use authentication
// 👉 It ONLY checks whether the token was generated by your server
    const decoded = jwt.verify(token, process.env.JWT_INVITE_SECRET);
    const { inviteId, workspaceId, inviteeId } = decoded;

    const invite = await Invite.findById(inviteId);
    if (!invite || invite.status !== "pending") {
      return res.status(400).json({ message: "Invite invalid or already used" });
    }

    if (invite.expiresAt < new Date()) {
      invite.status = "expired";
      await invite.save();
      return res.status(400).json({ message: "Invite expired" });
    }
     
    const workspace = await Workspace.findById(workspaceId);
    if (!workspace) return res.status(404).json({ message: "Workspace not found" });

    if (!workspace.members.includes(inviteeId)) {
      workspace.members.push(inviteeId);
      await workspace.save();
    }

    invite.status = "accepted";
    invite.usedAt = new Date();
    await invite.save();

    // Generate auth token
    const authToken = jwt.sign(
      { id: inviteeId },
      process.env.JWT_SECRET,
      { expiresIn: "7d" }
    );

    res.cookie("token", authToken, {
      httpOnly: true,
      maxAge: 7 * 24 * 60 * 60 * 1000,
    });

    res.json({ success: true, workspaceId });
  } catch (err) {
    console.error("Accept invite error:", err);
    return res.status(400).json({ message: "Invalid or expired invite" });
  }
};


export const getMyInvites = async (req, res) => {
  res.status(200).json({ invites: [] });
};
